language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install numpy
  - pip install matplotlib
  - pip install scipy
  - pip install requests
  - pip install enum34
  - python setup.py install

script:
  - pytest  # or py.test for Python versions 3.5 and below