language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install numpy
  - pip install matplotlib
  - pip install scipy
  - pip install requests
  - pip install cvxopt
  - pip install coveralls    # 代码覆盖率测试
  - python setup.py install

script:
  - pytest  # or py.test for Python versions 3.5 and below
  - coverage run --source=simple_ml setup.py test
after_success:
  - coveralls
