language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install numpy
  - pip install matplotlib
  - pip install scipy
  - python setup.py install

script:
  - pytest  # or py.test for Python versions 3.5 and below