title: "[ Simple Machine Learning ]"
description: A Machine Learning Algorithm Implementation
show_downloads: true
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge